import src.normalization.latin

fn test_normalize_latin() {
	assert latin.normalize_latin('') == ''
	assert latin.normalize_latin('0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz') == '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
	assert latin.normalize_latin('AĀBCČDEĒFGĢHIĪJKĶLĻMNŅOPQRSŠTUŪVXYWZŽ') == 'AABCCDEEFGGHIIJKKLLMNNOPQRSSTUUVXYWZZ'
	assert latin.normalize_latin('aābcčdeēfgģhiījkķlļmnņopqrsštuūvxywzž') == 'aabccdeefgghiijkkllmnnopqrsstuuvxywzz'
	assert latin.normalize_latin('ąĄčČęĘėĖįĮšŠųŲūŪžŽ') == 'aAcCeEeEiIsSuUuUzZ'
	assert latin.normalize_latin('ãẽĩõũñỹ') == 'aeiouny'
	assert latin.normalize_latin('ÃẼĨÕŨÑỸ') == 'AEIOUNY'
	assert latin.normalize_latin('àèìòùǹỳẁ') == 'aeiounyw'
	assert latin.normalize_latin('ÀÈÌÒÙǸỲẀ') == 'AEIOUNYW'
	assert latin.normalize_latin('áéíóúǵḱĺḿńṕŕśẃýź') == 'aeiougklmnprswyz'
	assert latin.normalize_latin('ÁÉÍÓÚǴḰĹḾŃṔŔŚẂÝŹ') == 'AEIOUGKLMNPRSWYZ'
	assert latin.normalize_latin('âêîôûĉĝĥĵŝŷŵẑ') == 'aeioucghjsywz'
	assert latin.normalize_latin('ÂÊÎÔÛĈĜĤĴŜŶŴẐ') == 'AEIOUCGHJSYWZ'
	assert latin.normalize_latin('äëïöüḧẗẍÿẅ') == 'aeiouhtxyw'
	assert latin.normalize_latin('ÄËÏÖÜḦẌŸẄ') == 'AEIOUHXYW'
	assert latin.normalize_latin('åÅ') == 'aA'
	assert latin.normalize_latin('æÆ') == 'aeAE'
	assert latin.normalize_latin('çÇ') == 'cC'
	assert latin.normalize_latin('øØ') == 'oO'
	assert latin.normalize_latin('ß') == 's'
	assert latin.normalize_latin('В начале') == 'В начале'
	assert latin.normalize_latin('最初有道') == '最初有道'
	assert latin.normalize_latin('לפניכם') == 'לפניכם'
	// TODO: assert latin.normalize_latin('œŒ') == 'oeOE'
}
