name: BuildOnly with skip-unused and autofree

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Install V
        uses: vlang/setup-v@v1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v2

      - name: Build ${{ github.event.repository.name }}
        run: v -skip-unused -autofree .
