name: New changes validation

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  set-up-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Install V
        uses: vlang/setup-v@v1.1
        with:
          check-latest: true

      - name: Checkout ${{ github.event.repository.name }}
        uses: actions/checkout@v3
  build:
    needs: set-up-environment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        trimming: [, -skip-unused]
        optimization: [, -prod]
        memory-management: [, -autofree]
      steps:
        - name: ${{ matrix.trimming }} ${{ matrix.optimization }} ${{ matrix.memory-management }} build
          run: v -shared ${{ matrix.trimming }} ${{ matrix.optimization }} ${{ matrix.memory-management }} .
